### ISSUE TITLE
Function that returns a file in various size conversions (bytes, kb, mb)

### ISSUE THREAD

**Issue by marcobeltempo** [marcobeltempo/fileside#2]
This function should be able to extract a filename from a path as well as calculate the file size.
Example: `user/marco/mydata.txt`
mydatat.txt 250 bytes

The node module [filesize](https://www.npmjs.com/package/filesize) would be great for this implementation.

**Comment by MPierre9** [comment]
Hello, I'd like to take on this issue if possible

**Comment by marcobeltempo** [comment]
@MPierre9 I ended up implementing the file size feature in the [initial commit](https://github.com/marcobeltempo/fileside/commit/3e52339459b1d461dee1525cfc6e03af48be41d6#diff-bb503f3d9047bcd4a5730559f1e16560). 
Maybe you could work on changing the output from `512 B` to say `512 Bytes` or even display the size in kb and bytes

**Comment by MPierre9** [comment]
@marcobeltempo, managed to get the code to display Bytes instead of B as well as Kilobytes. Right now the function just returns the number however it can be changed to return a string saying `1024 Kilobytes `for example. Here is the code:
```

     fs.stat(file, function (err, stats) {
        var fileStats = [
          'Ananalyzing file from ' + file,
          'Directory: ' + path.win32.dirname(file), //gets the files directroy 
          'Filename: ' + path.win32.basename(file), //gets file name
          'Extension: ' + path.win32.extname(file), //gets file extension
          'Size:' + stats.size + ' Bytes' + ' ' + getKilobytes(stats.size) + ' Kilobytes',        //gets file size and converst to readable bytes
          'File contents: ' + data                  //contents in the file
        ]

        res.render('index', {
          title: 'Fileside',
          stats: fileStats
        });
        //For debugging
        console.log("Directory: ", path.win32.dirname(file));
        console.log("Filename: ", path.win32.basename(file));
        console.log("Extension: ", path.win32.extname(file));
        console.log('Size:', filesize(stats["size"]));
        console.log("File contents: ", data);
      });
    }

  });

});

function getKilobytes(bytes) {
  
  var convertToKiloBytes = bytes / 1024
  var kilobytes = convertToKiloBytes.toFixed(2)

  return kilobytes;
}
```

![new bytes](https://user-images.githubusercontent.com/27080760/31741839-bafafd72-b423-11e7-8256-438de3d7c62a.JPG)

**Comment by marcobeltempo** [comment]
Nice work! @MPierre9 I think we should leave it the way it is returning the size in KB. 
Submit a pull request and I'll look it over

**Comment by marcobeltempo** [comment]
#6
