### ISSUE TITLE
Readme Suggestions and Revisions

### ISSUE THREAD

**Issue by MPierre9** [marcobeltempo/fileside#8]
Your README looks really good! Here are some suggestions to review: 

1. [As of now fileside can only process local files but __look__ to expand to additional features such as drag and drop support.](https://github.com/marcobeltempo/fileside#fileside)
      * change to **is looking**
1. [Prerequisites Section](https://github.com/marcobeltempo/fileside#prerequisites)
    * Maybe add links on where to download node.js and other software used to develop the project
    * Example: [node v8.9](https://nodejs.org/en/) and [Visual Studio 2017](https://www.visualstudio.com/downloads/)

Other than that is looks pretty good 👍

**Comment by marcobeltempo** [comment]
@MPierre9 thanks for the feedback! 
I'll hopefully be pushing a ton of changes in the next day along with a more detailed ReadMe
